--- Warehose CREATE

CREATE WAREHOUSE SAMPLE_KARTHIK
WITH 
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SAMPLE_KARTHIK;

--Database CREATE

CREATE DATABASE RETAIL_DWH;

use database retail_dwh;

-- schema CREATE


CREATE SCHEMA RAW;
CREATE SCHEMA STAGE;
CREATE SCHEMA ANALYTICS;


--File format 


CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER = 1;

-- Stage creation

CREATE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_STAGE;



--- RAW TABLE CREATION

CREATE TABLE RAW.SUPERSTORE_RAW (
SHIP_MODE STRING,
SEGMENT STRING,
COUNTRY STRING,
CITY STRING,
STATE STRING,
POSTAL_CODE STRING,
REGION STRING,
CATEGORY STRING,
SUB_CATEGORY STRING,
SALES FLOAT,
QUANTITY INT,
DISCOUNT FLOAT,
PROFIT FLOAT
);


-- Loading data

COPY INTO RAW.SUPERSTORE_RAW
FROM @RETAIL_STAGE/SampleSuperstore.csv;

--- Snowpipe

-- CREATE PIPE SALES_PIPE
-- AUTO_INGEST = FALSE
-- AS
-- COPY INTO RAW.SUPERSTORE_RAW
-- FROM @RETAIL_STAGE
-- FILE_FORMAT = CSV_FORMAT;


--- customer dimension


CREATE TABLE ANALYTICS.DIM_CUSTOMER AS
SELECT DISTINCT
SEGMENT,
COUNTRY,
CITY,
STATE,
REGION
FROM RAW.SUPERSTORE_RAW;


--- product dimension

CREATE TABLE ANALYTICS.DIM_PRODUCT AS
SELECT DISTINCT
CATEGORY,
SUB_CATEGORY
FROM RAW.SUPERSTORE_RAW;


--Fact Table


CREATE TABLE ANALYTICS.FACT_SALES AS
SELECT
SEGMENT,
CATEGORY,
SUB_CATEGORY,
SALES,
QUANTITY,
DISCOUNT,
PROFIT
FROM RAW.SUPERSTORE_RAW;


--- Data masking

CREATE MASKING POLICY REGION_MASK AS (val STRING)
RETURNS STRING ->
CASE
WHEN CURRENT_ROLE() IN ('ANALYST_ROLE')
THEN val
ELSE 'MASKED'
END;

ALTER TABLE ANALYTICS.DIM_CUSTOMER
MODIFY COLUMN REGION
SET MASKING POLICY REGION_MASK;


--- Zero copy cloning

CREATE TABLE ANALYTICS.FACT_SALES_CLONE
CLONE ANALYTICS.FACT_SALES;


-- Streams

CREATE STREAM SALES_STREAM 
ON TABLE RAW.SUPERSTORE_RAW;

-- Tasks


CREATE TASK LOAD_TASK
WAREHOUSE = sample_karthik
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SALES_STREAM') 
AS
INSERT INTO ANALYTICS.FACT_SALES
SELECT SEGMENT, CATEGORY, SUB_CATEGORY, SALES, QUANTITY, DISCOUNT, PROFIT
FROM SALES_STREAM; 

ALTER TASK LOAD_TASK RESUME;


-- view

CREATE VIEW ANALYTICS.SALES_VIEW AS
SELECT 
CATEGORY,
SUM(SALES) TOTAL_SALES,
SUM(PROFIT) TOTAL_PROFIT
FROM ANALYTICS.FACT_SALES
GROUP BY CATEGORY;


-- Materialized view


CREATE MATERIALIZED VIEW ANALYTICS.SALES_MV AS
SELECT 
REGION,
SUM(SALES) TOTAL_SALES
FROM RAW.SUPERSTORE_RAW
GROUP BY REGION;


-- Time travel


SELECT * FROM RAW.SUPERSTORE_RAW
AT (OFFSET => -60*10);

-- Clustering

ALTER TABLE ANALYTICS.FACT_SALES
CLUSTER BY (CATEGORY);


-- Creating roles


CREATE ROLE ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE SAMPLE_KARTHIK TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA RETAIL_DWH.ANALYTICS TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE RETAIL_DWH TO ROLE ANALYST_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;


-- Resource monitor(cost)


CREATE RESOURCE MONITOR RETAIL_MONITOR
WITH CREDIT_QUOTA = 50
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS 
ON 80 PERCENT DO NOTIFY
ON 100 PERCENT DO SUSPEND;


ALTER WAREHOUSE SAMPLE_KARTHIK
SET RESOURCE_MONITOR = RETAIL_MONITOR;


--- Data sharing

CREATE SHARE RETAIL_SHARE;
GRANT USAGE ON DATABASE RETAIL_DWH TO SHARE RETAIL_SHARE;
GRANT USAGE ON SCHEMA RETAIL_DWH.ANALYTICS TO SHARE RETAIL_SHARE;
GRANT SELECT ON TABLE RETAIL_DWH.ANALYTICS.FACT_SALES TO SHARE RETAIL_SHARE;